Fix name assignment, database is still broken: *Currently any authenticate attempts should return a query on the test database (created locally on my machine) displaying a single entry...
/home/git/jim/lib/authHandler.coffee:14
      return base.collection.find();
                             ^
TypeError: Object function (collectionName, options, callback) {
  var self = this;
  if(typeof options === "function") { callback = options; options = {}; }
  // Execute safe

  if(options && (options.strict)) {
    self.collectionNames(collectionName, function(err, collections) {
      if(err != null) return callback(err, null);

      if(collections.length == 0) {
        return callback(new Error("Collection " + collectionName + " does not exist. Currently in
safe mode."), null);
      } else {
        try {
          var collection = new Collection(self, collectionName, self.pkFactory, options);
        } catch(err) {
          return callback(err, null);
        }
        return callback(null, collection);
      }
    });
  } else {
    try {
      var collection = new Collection(self, collectionName, self.pkFactory, options);
    } catch(err) {
      if(callback == null) {
        throw err;
      } else {
        return callback(err, null);
      }
    }

    // If we have no callback return collection object
    return callback == null ? collection : callback(null, collection);
  }
} has no method 'find'
  at Object.authHandler.authenticate (/home/git/jim/lib/authHandler.coffee:36:3, <js>:14:30)
  at Object.jimHandler.authenticate (/home/git/jim/lib/jimHandler.coffee:73:3, <js>:40:26)
  at Object.jimHandler.review (/home/git/jim/lib/jimHandler.coffee:50:31, <js>:16:33)
  at Object.KirkNode.ReviewJson (/home/git/jim/lib/KirkNode.coffee:151:3, <js>:99:25)
  at Socket.<anonymous> (/home/git/jim/lib/KirkNode.coffee:107:6, <js>:65:29)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)